name: huizong

on:
  schedule:
    - cron: '31 */2 * * *'  # 每2小时执行一次
  workflow_dispatch:

jobs:
  generate-and-push:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出当前仓库
      - name: Checkout source repo
        uses: actions/checkout@v4

      # 第二步：设置PHP环境
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      # 第三步：生成EPG文件
      - name: 生成faintv.txt
        run: |
          php main.php
          ls -l faintv.txt
          echo "文件生成时间：" $(date -R)

      # 第四步：检出目标仓库
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: zzq1234567890/huanlekan
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo

      # 第五步：同步文件
      - name: Sync files
        run: |
          # 复制新文件到目标仓库
          cp -vf faintv.txt target-repo/faintv.txt
          
          # 进入目标仓库目录
          cd target-repo
          
          # 配置Git身份
          git config user.name "EPG Auto Updater"
          git config user.email "epg-bot@users.noreply.github.com"
          
          # 检查文件差异
          if ! git diff --exit-code faintv.txt; then
            git add faintv.txt
            git commit -m "EPG自动更新: $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M')"
            git push origin main
            echo "更新已推送"
          else
            echo "没有检测到变更"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
